services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /pgdata
    volumes:
      - /Use  rs/kunalbhatia/Desktop/super-30/time-scale-db:/pgdata
    restart: unless-stopped
